### ISSUE TITLE
Container group code is incorrect

### ISSUE THREAD

**Issue by Mikanebu** [datasets/ISO-Container-Codes#4]
It is reported here https://github.com/datahq/datahub-qa/issues/205.

## Acceptance criteria

* [x] container group is valid according to the source

## Tasks

* [x] update `iso-container-group.csv`
* [x] update `iso-container-codes.csv` groups column

**Comment by Mikanebu** [comment]
FIXED, updated ISO container group codes according to the Container Container website http://www.containercontainer.com/ISO6346.aspx
